config/routes.rb
Rails.application.routes.draw do
  
  root 'homes#index'
  
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    registrations: 'users/registrations',
  }
  
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    registrations: 'admins/registrations',
  }
  
  devise_for :temples, controllers: {
    sessions:      'temples/sessions',
    registrations: 'temples/registrations',
  }
  
  namespace :admins do
    resources   :users, only: %i(index show destroy edit update) do
      get 'reservations', on: :member
      get 'reservation',  on: :member
    end
    resources :temples, only: %i(index show destroy edit update)
  end
  
  resources :reservations, only: %i(new create index show destroy update) do
    get 'complete', on: :member
  end
  
  namespace :temples do
    resources :users, only: %i(index show) do
      resources :reservations, only: %i(show index destroy)
    end
    resources :reservations,  only: %i(new create edit update) do
      patch :delete_user,     on:   :member
      get   'all',            on:   :collection
    end
    get     'reservations/month'   =>  'reservations#month'
    get     'reservations/week'    =>  'reservations#week'
    get     'reservations_by_day', to: 'reservations#reservations_by_day', as: 'reservations_by_day'
    delete  'reservations_by_day', to: 'reservations#destroy_by_day',      as: 'destroy_reservations_by_day'
  end
  
  resources :temples, only: [:index, :show] do
    get 'management', to: :collection
  end
  
  post  '/temples/:id/assign_temple', to: 'users#assign_temple',   as: 'assign_temple'
  patch '/users/unassign_temple',     to: 'users#unassign_temple', as: 'unassign_temple'
  
  resources :articles
  resources :posts
  resources :users,  only: [:show]
  resources :admins, only: [:index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/admins/index.html.erb
<div class="container">
    
  <h2 class="text-center mt-5 mb-5">管理画面</h2>

  <div class="card-list row d-flex justify-content-md-between justify-content-center pt-5">
      
    <div class="card management text-center col-lg-3 col-md-5 col-sm-8 col-10 mb-5">
      <div class="card-body" onclick="location.href='<%= posts_path %>';">
        <div class="card-icon">
          <i class="fas fa-book-open fa-5x" style='color:lightgreen;'></i>
        </div>
        <div class="card-text">
          <p>お知らせ管理</p>
        </div>
      </div>
    </div>
    
    <div class="card management text-center col-lg-3 col-md-5 col-sm-8 col-10 mb-5">
      <div class="card-body" onclick="location.href='<%= admins_users_path %>';">
        <div class="card-icon">
          <i class="fas fa-user fa-5x" style='color:skyblue;'></i>
        </div>
        <div class="card-text">
          <p>ユーザー管理</p>
        </div>
      </div>
    </div>
    
    <%#= link_to "寺院登録", new_temple_registration_path %>
    
    <div class="card management text-center col-lg-3 col-md-5 col-sm-8 col-10 mb-5">
      <div class="card-body" onclick="location.href='<%= admins_temples_path %>';">
        <div class="card-icon">
          <i class="fas fa-vihara fa-5x" style='color:orange;'></i>
        </div>
        <div class="card-text">
          <p>寺院管理</p>
        </div>
      </div>
    </div>
    
  </div>

</div>