config/routes.rb
Rails.application.routes.draw do
  
  root 'homes#index'
  
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    registrations: 'users/registrations',
  }
  
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    registrations: 'admins/registrations',
  }
  
  devise_for :temples, controllers: {
    sessions:      'temples/sessions',
    registrations: 'temples/registrations',
  }
  
  namespace :admins do
    resources   :users, only: %i(index show destroy edit update) do
      get 'reservations', on: :member
      get 'reservation',  on: :member
    end
    resources :temples, only: %i(index show destroy edit update)
  end
  
  resources :reservations, only: %i(new create index show destroy update) do
    get 'complete', on: :member
  end
  
  namespace :temples do
    resources :users, only: %i(index show) do
      resources :reservations, only: %i(show index destroy)
    end
    resources :reservations,  only: %i(new create edit update) do
      patch :delete_user,     on:   :member
      get   'all',            on:   :collection
    end
    get     'reservations/month'   =>  'reservations#month'
    get     'reservations/week'    =>  'reservations#week'
    get     'reservations_by_day', to: 'reservations#reservations_by_day', as: 'reservations_by_day'
    delete  'reservations_by_day', to: 'reservations#destroy_by_day',      as: 'destroy_reservations_by_day'
  end
  
  resources :temples, only: [:index, :show] do
    get 'management', to: :collection
  end
  
  post  '/temples/:id/assign_temple', to: 'users#assign_temple',   as: 'assign_temple'
  patch '/users/unassign_temple',     to: 'users#unassign_temple', as: 'unassign_temple'
  
  resources :articles
  resources :posts
  resources :users,  only: [:show]
  resources :admins, only: [:index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  validates :name, presence: true
  validates :name_kana, name_kana: true
  validates :postal_code, allow_blank: true, format: { with: /\A\d{7}\z/, message: "は7桁の数字のみ入力してください。" }
  validates :phone_number, phone_number: true
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  belongs_to :temple, optional: true
  has_many :reservations, dependent: :destroy
  
  #ユーザーを部分一致で検索
  def self.search(search)
    return User.all unless search
    User.where(['name LIKE ?', "%#{search}%"])
  end
  
  #ユーザーが寺院に所属しているか判定
  def has_temple?
    temple.present?
  end
  
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  before_action :authenticate_admin!
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def show
    @user = User.find(params[:id])
    @temple = @user.temple
  end
  
  def index
    @reservation = Reservation.all
    @users = User.search(params[:search]).order(:name_kana)
  end
  
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admins_user_path(@user), notice: 'ユーザー情報を更新しました。'
    else
      flash.now[:danger] = "ユーザー情報を更新できませんでした。"
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to admins_users_path, notice: 'ユーザーを削除しました。'
    else
      flash.now[:danger] = "ユーザーを削除できませんでした。"
      render :edit
    end
  end
  
  def reservations
    @user = User.find(params[:id])
    @reservations = Reservation.where(user_id: @user.id).where("start_time >= ?", Time.zone.today.beginning_of_day).order(:start_time)
  end
  
  def reservation
    @reservation = Reservation.find(params[:id])
    @temple = @reservation.temple
    @user = @reservation.user
  end


  private

  def user_params
    if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
    params.require(:user).permit(:name, :name_kana, :postal_code, :prefecture_code, :city, :street, :other_address, :email, :phone_number, :password, :password_confirmation).except(:current_password)
  end
  
  def configure_permitted_parameters
    if admin_signed_in?
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :name_kana, :postal_code, :prefecture_code, :city, :street, :other_address, :email, :phone_number])
    else
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :name_kana, :postal_code, :prefecture_code, :city, :street, :other_address, :email, :phone_number, :password, :password_confirmation, :current_password])
    end
  end
  
  
end
  

app/controllers/temples/users_controller.rb
class Temples::UsersController < ApplicationController
  before_action :authenticate_temple!
  
  def index
    @temple = current_temple
    subquery = @temple.reservations.select(:user_id)
    user = User.where(id: @temple.users).or(User.where(id: subquery))
    @users = user.search(params[:search]).order(:name_kana)
  end
  
  def show
    @temple = current_temple
    @user = User.find_by(id: params[:id])
    unless @user.present? && (@temple.users.include?(@user) || @temple.reservations.exists?(user_id: @user.id))
      redirect_to temple_path(@temple), alert: "閲覧する権限がありません。"
    end
  end
  
  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
    

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  
  protected

  def after_update_path_for(resource)
    user_path(resource)
  end
  
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:show]
  
  def show
    @user = User.find(params[:id])
    @temple = @user.temple
  end
  
  def assign_temple
    @temple = Temple.find(params[:id])
    if current_user.has_temple?
      redirect_to user_path(current_user), alert: "所属できる寺院は1つまでです。"
    else
      current_user.update(temple_id: @temple.id)
      redirect_to temple_path(@temple), notice: "寺院に所属しました。"
    end
  end
  
  def unassign_temple
    current_user.update(temple_id: nil)
    redirect_to user_path(current_user), notice: "所属を解除しました。"
  end
  
  private
  
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless @user == current_user
    end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/users/edit.html.erb
<div class="container">
  <div class="row col-md-10 clo-sm-11 mx-auto">
    
    <div class="title text-center mt-5 mb-4">
      <h2>登録情報の変更</h2>
    </div>
    
    <%= form_with(model: [@user], url: admins_user_path(@user), method: :patch) do |f| %>
      <div class="<%= 'error-box' if @user.errors.any? %>">
        <%= render "layouts/error", model: @user %>
      </div>

      <table class="table table-responsive form-table">
        <tbody>
        
          <tr class="field">
            <th><%= f.label :name, "氏名" %></th>
            <td class="form-group <%= 'has-error' if @user.errors.include?(:name) %>">
              <%= f.text_field :name, class: 'form-control', id: 'edit-admin-user-name' %>
            </td>
          </tr>
      
          <tr class="field">
            <th><%= f.label :name_kana, "氏名(カナ)" %></th>
            <td class="form-group <%= 'has-error' if @user.errors.include?(:name_kana) %>">
              <%= f.text_field :name_kana, class: 'form-control', id: 'edit-admin-user-name-kana' %>
            </td>
          </tr>
  
          <tr class="field">
            <th><%= f.label :postal_code, "郵便番号" %></th>
            <td class="form-group <%= 'has-error' if @user.errors.include?(:postal_code) %>">
              <%= f.text_field :postal_code, class: 'form-control', id: 'edit-admin-user-postal-code' %>
            </td>
          </tr>
  
          <tr class="field">
            <th><%= f.label :prefecture_code, "都道府県" %></th>
            <td><%= f.collection_select :prefecture_code, JpPrefecture::Prefecture.all, :name, :name, class: 'form-control' %></td>
          </tr>
  
          <tr class="field">
            <th><%= f.label :city, "市区町村" %></th>
            <td><%= f.text_field :city, class: 'form-control' %></td>
          </tr>
  
          <tr class="field">
            <th><%= f.label :street, "番地" %></th>
            <td><%= f.text_field :street, class: 'form-control' %></td>
          </tr>
  
          <tr class="field">
            <th><%= f.label :other_address, "建物名・部屋番号" %></th>
            <td><%= f.text_field :other_address, class: 'form-control' %></td>
          </tr>

          <tr class="field">
            <th><%= f.label :email, "メールアドレス" %></th>
            <td class="form-group <%= 'has-error' if @user.errors.include?(:email) %>">
              <%= f.email_field :email, autocomplete: "email", class: 'form-control', id: 'edit-admin-user-email' %>
            </td>
          </tr>
  
          <tr class="field">
            <th><%= f.label :phone_number, "電話番号" %></th>
            <td class="form-group <%= 'has-error' if @user.errors.include?(:phone_number) %>">
              <%= f.text_field :phone_number, class: 'form-control', id: 'edit-admin-user-phone-number' %>
            </td>
          </tr>
      
        </tbody>
      </table>
      
      <div class="actions pt-4">
        <%= f.submit "変更", class: "btn btn-outline-secondary w-100" %>
      </div>
      
    <% end %>
    
    <div class="text-center mt-5 mb-4">
      <h3>アカウント削除</h3>
    </div>
    
    <div class="text-center">
      <p>アカウントを削除しますか？</p>
      <div class="text-center">
        <%= button_to admins_user_path(@user), data: { confirm: "本当に削除しますか？", turbo_confirm: "本当に削除しますか？" }, method: :delete, class: "btn btn-outline-danger" do %>
          <i class="fas fa-user-slash"></i> 削除
        <% end %>
      </div>
    </div>
    
    <div class="text-center mt-3">
      <%= link_to "キャンセル", admins_user_path(@user) %>
    </div>

  </div>
</div>


<%= javascript_pack_tag 'admin_user_errors' %>

app/views/admins/users/index.html.erb
<div class="container">
  <div class="row col-md-10 clo-sm-11 mx-auto">
    
    <div class="text-center mt-5 mb-4">
      <h2>ユーザー管理画面</h2>
    </div>
    
    <div class="user_search">
      <%= form_tag(admins_users_path, method: :get, class: "input-group") do %>
        <%= text_field_tag(:search, params[:search], class: "form-control", placeholder: "名前を入力してください") %>
        <%= button_tag(type: "submit", class: "btn btn-outline-primary", id: "button-addon2") do %>
          <i class="fas fa-search"></i> 検索
        <% end %>
      <% end %>
    </div>
    
    <table class="table table-responsive mt-5 text-center">
      <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td>
          <%= link_to admins_user_path(user.id) do %>
            <button type="button" class="btn btn-sm btn-outline-primary">
              <i class="fas fa-id-card"></i> ユーザー詳細
            </button>
          <% end %>
        </td>
        <td>
          <%= link_to reservations_admins_user_path(user.id) do %>
            <button type="button" class="btn btn-sm btn-outline-primary">
              <i class="fas fa-list-ul"></i> 予約一覧
            </button>
          <% end %>
        </td>
      </tr>
      <% end %>
    </table>
    
  </div>
</div>

app/views/admins/users/reservation.html.erb
<div class="container">
  <div class="row col-md-10 clo-sm-11 mx-auto">
    
    <div class="title text-center mt-5 mb-4">
      <h2>予約詳細画面</h2>
    </div>
    
    <table class="table table-responsive user-reservation-table mt-3">
      <tbody>
      
        <tr class="field">
          <th>日付：</th>
          <td><%= @reservation.day.strftime('%Y年%m月%d日') %></td>
        </tr>
      
        <tr class="field">
          <th>寺院：</th>
          <td><%= link_to @temple.name, temple_path(@temple.id) %></td>
        </tr>
      
        <tr class="field">
          <th>時間：</th>
          <td><%= @reservation.time %></td>
        </tr>
      
        <tr class="field">
          <% if @reservation.user.present? %>
            <th>ユーザー名：</th>
            <td><%= @reservation.user.name %></td>
          <% elsif @reservation.new_user_name.present? %>
            <th>ユーザー名：</th>
            <td><%= @reservation.new_user_name %></td>
          <% elsif @reservation.temple.present? %>
            <th>ユーザー名：</th>
            <td><%= @reservation.temple.name %></td>
          <% end %>
        </tr>
      
        <tr class="field">
          <th>ステータス：</th>
          <td><%= @reservation.reservation_status %></td>
        </tr>
      
        <% if @reservation.comment.present? %>
        <tr class="field">
          <th>備考欄：</th>
          <td><%= @reservation.comment %></td>
        </tr>
        <% end %>
      
      </tbody>
    </table>
    
    <div class="text-center mt-3">
      <%= link_to reservations_admins_user_path(@user) do %>
        <button type="button" class="btn btn-sm btn-outline-primary">
          <i class="fas fa-list-ul"></i> 予約一覧
        </button>
      <% end %>
    </div>
    
  </div>
</div>

app/views/admins/users/reservations.html.erb
<div class="container">
  <div class="row col-md-10 clo-sm-11 mx-auto">
    
    <div class="title text-center mt-5 mb-4">
      <h2><%= @user.name %>様の予約一覧画面</h2>
    </div>
    
    <div class="text-center">
      <%= link_to admins_user_path(@user) do %>
        <button type="button" class="btn btn-outline-secondary">
          <i class="fas fa-id-card"></i><%= " #{@user.name}様の登録情報" %>
        </button>
      <% end %>
    </div>
    
    <div class="text-center mt-3">
      <% if @reservations.count > 0 %>
        <p>下記の日時で予約されています。</p>
    
        <table class="table table-responsive mt-3">
          <thead>
            <th>日付</th>
            <th>寺院</th>
            <th>時間</th>
            <th>ステータス</th>
            <th></th>
          </thead>
          <tbody>
            <% @reservations.each do |reservation| %>
              <tr>
                <td><%= reservation.day.strftime('%Y年%m月%d日') %></td>
                <td><%= link_to reservation.temple.name, admins_temple_path(reservation.temple_id) %></td>
                <td><%= reservation.time %></td>
                <td><%= reservation.reservation_status %></td>
                <td><%= link_to "詳細", reservation_admins_user_path(reservation), class: "btn btn-sm btn-outline-primary" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
    
    <% else %>
        <p>予約がありません。</p>
      <% end %>
    </div>
    
  </div>
</div>

app/views/admins/users/show.html.erb
<div class="container">
  <div class="row col-md-10 clo-sm-11 mx-auto">
    
    <div class="title text-center mt-5 mb-4">
      <h2>登録情報</h2>
    </div>
    
    <div class="d-flex justify-content-between">
      <div>
        <p>
          所属寺院: 
          <% if @user.temple %>
            <%= link_to @user.temple.name, admins_temple_path(@temple.id) %>
          <% else %>
            なし
          <% end %>
        </p>
      </div>
      <div>
        <%= link_to reservations_admins_user_path(@user) do %>
          <button type="button" class="btn btn-outline-primary">
            <i class="fas fa-list-ul"></i><%= " #{@user.name}様の予約一覧" %>
          </button>
        <% end %>
      </div>
    </div>
    
    <table class="table table-responsive user-table">
      <tbody>
      
        <tr class="field">
          <th>氏名</th>
          <td><%= @user.name %></td>
        </tr>
      
        <tr class="field">
          <th>氏名(カナ)</th>
          <td><%= @user.name_kana %></td>
        </tr>
      
        <tr class="field">
          <th>郵便番号</th>
          <td><%= number_with_hyphen_format(@user.postal_code) %></td>
        </tr>
      
        <tr class="field">
          <th>都道府県</th>
          <td><%= @user.prefecture_code %></td>
        </tr>
      
        <tr class="field">
          <th>市区町村</th>
          <td><%= @user.city %></td>
        </tr>
      
        <tr class="field">
          <th>番地</th>
          <td><%= @user.street %></td>
        </tr>
      
        <tr class="field">
          <th>建物名・部屋番号</th>
          <td><%= @user.other_address %></td>
        </tr>
      
        <tr class="field">
          <th>メールアドレス</th>
          <td><%= @user.email %></td>
        </tr>
      
        <tr class="field">
          <th>電話番号</th>
          <td><%= number_with_hyphen_format(@user.phone_number) %></td>
        </tr>
      
      </tbody>
    </table>
    
    <div class="text-center mt-3">
      <%= link_to edit_admins_user_path(@user.id) do %>
        <button type="button" class="btn btn-outline-secondary">
          <i class="fas fa-user-edit"></i> ユーザー情報編集
        </button>
      <% end %>
    </div>
    
  </div>
</div>