config/routes.rb
Rails.application.routes.draw do
  
  root 'homes#index'
  
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    registrations: 'users/registrations',
  }
  
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    registrations: 'admins/registrations',
  }
  
  devise_for :temples, controllers: {
    sessions:      'temples/sessions',
    registrations: 'temples/registrations',
  }
  
  namespace :admins do
    resources   :users, only: %i(index show destroy edit update) do
      get 'reservations', on: :member
      get 'reservation',  on: :member
    end
    resources :temples, only: %i(index show destroy edit update)
  end
  
  resources :reservations, only: %i(new create index show destroy update) do
    get 'complete', on: :member
  end
  
  namespace :temples do
    resources :users, only: %i(index show) do
      resources :reservations, only: %i(show index destroy)
    end
    resources :reservations,  only: %i(new create edit update) do
      patch :delete_user,     on:   :member
      get   'all',            on:   :collection
    end
    get     'reservations/month'   =>  'reservations#month'
    get     'reservations/week'    =>  'reservations#week'
    get     'reservations_by_day', to: 'reservations#reservations_by_day', as: 'reservations_by_day'
    delete  'reservations_by_day', to: 'reservations#destroy_by_day',      as: 'destroy_reservations_by_day'
  end
  
  resources :temples, only: [:index, :show] do
    get 'management', to: :collection
  end
  
  post  '/temples/:id/assign_temple', to: 'users#assign_temple',   as: 'assign_temple'
  patch '/users/unassign_temple',     to: 'users#unassign_temple', as: 'unassign_temple'
  
  resources :articles
  resources :posts
  resources :users,  only: [:show]
  resources :admins, only: [:index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admins/temples_controller.rb
class Admins::TemplesController < ApplicationController
  before_action :authenticate_admin!
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def show
    @temple = Temple.find(params[:id])
    @articles = @temple.articles.order(created_at: :desc).limit(3)
    set_latitude_longitude(@temple)
  end
  
  def index
    @reservation = Reservation.all
    @temples = Temple.search(params[:search]).order(:name_kana)
  end
  
  def edit
    @temple = Temple.find(params[:id])
  end

  def update
    @temple = Temple.find(params[:id])
    if @temple.update(temple_params)
      redirect_to admins_temple_path(@temple), notice: '寺院情報を更新しました。'
    else
      flash.now[:danger] = "寺院情報を更新できませんでした。"
      render :edit
    end
  end

  def destroy
    @temple = Temple.find(params[:id])
    if @temple.destroy
      redirect_to admins_temples_path, notice: '寺院を削除しました。'
    else
      flash.now[:danger] = "寺院を削除できませんでした。"
      render :edit
    end
  end
  
  def reservations
    @temple = Temple.find(params[:id])
    @reservations = Reservation.where(temple_id: @temple.id).where("start_time >= ?", Time.zone.today.beginning_of_day).order(:start_time)
  end
  
  def reservation
    @reservation = Reservation.find(params[:id])
    @temple = @reservation.temple
    @user = @reservation.user
  end


  private
  
  # 寺院の住所から緯度と経度を取得しGoogleMapに表示させる
  def set_latitude_longitude(temple)
    result = Geocoder.search(temple.address).first
    if result.present?
      temple.latitude = result.latitude
      temple.longitude = result.longitude
    end
  end

  def temple_params
    if params[:temple][:password].blank? && params[:temple][:password_confirmation].blank?
      params[:temple].delete(:password)
      params[:temple].delete(:password_confirmation)
    end
    params.require(:temple).permit(:name, :name_kana, :postal_code, :prefecture_code, :address, :email, :phone_number, :password, :password_confirmation).except(:current_password)
  end
  
  def configure_permitted_parameters
    if admin_signed_in?
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :name_kana, :postal_code, :prefecture_code, :address, :email, :phone_number])
    else
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :name_kana, :postal_code, :prefecture_code, :address, :email, :phone_number, :password, :password_confirmation, :current_password])
    end
  end
  
  
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :destroy]

  def new
    @reservation = Reservation.new
    @temple = params[:temple_id]
    @day = params[:day]
    @time = params[:time]
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.temple = Temple.find(params[:reservation][:temple_id])
    temple_id = params[:reservation][:temple_id]
    @reservation.temple_id = temple_id
    @start_time = Time.zone.parse(params[:reservation][:day] + " " + params[:reservation][:time])
    @reservation.start_time = @start_time
    @reservation.end_time = @reservation.start_time + 1.hour
    @end_time = @reservation.end_time
    if Reservation.reserved?(@start_time, @end_time, temple_id)
      flash[:alert] = "指定された日時は既に予約済みです。"
      date = Date.current
      redirect_to temples_reservations_week_path(date: date, temple_id: temple_id)
    elsif @reservation.save
      flash[:success] = "下記の日時で予約を行いました。"
      redirect_to complete_reservation_path(@reservation.id)
    else
      render :new
    end
  end

  def complete
    @reservation = Reservation.find(params[:id])
    @temple = @reservation.temple
  end

  def show
    @reservation = Reservation.find(params[:id])
    @temple = @reservation.temple
  end

  def index
    @reservations = Reservation.where(user_id: current_user).where("start_time >= ?", Time.zone.today.beginning_of_day).order(:start_time)
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    if @reservation.destroy
      redirect_to reservations_path(current_user), flash: { danger: "予約を削除しました。" }
    else
      flash.now[:danger] = "予約の削除に失敗しました。"
      render :show
    end
  end


  private

  def reservation_params
    params.require(:reservation).permit(:day, :time, :user_id, :temple_id, :start_time, :end_time, :admin_id, :status, :start_date, :end_date, :new_user_name, :comment)
  end

end

app/controllers/temples/confirmations_controller.rb
# frozen_string_literal: true

class Temples::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/temples/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Temples::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/temples/passwords_controller.rb
# frozen_string_literal: true

class Temples::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/temples/registrations_controller.rb
# frozen_string_literal: true

class Temples::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  
  protected

  def after_update_path_for(resource)
    temple_path(resource)
  end
  
end

app/controllers/temples/reservations_controller.rb
class Temples::ReservationsController < ApplicationController
  before_action :authenticate_temple!, only: [:new, :create, :index, :show, :edit, :update, :destroy, :reservations_by_day, :destroy_by_day, :all, :delete_user]

  def new
    @user_id = params[:user_id]
    @user = User.find_by(id: @user_id)
    @reservation = Reservation.new
    @day = params[:day]
    @time = params[:time]
  end

  def create
    if params[:reservation][:user_id] == 'new'
      @reservation = Reservation.new(reservation_params.merge(new_user_name: params[:reservation][:new_user_name]))
    else
      @reservation = Reservation.new(reservation_params)
    end
    @start_time = Time.zone.parse(params[:reservation][:day] + " " + params[:reservation][:time])
    @reservation.start_time = @start_time
    @end_time = Time.zone.parse(params[:reservation][:day] + " " + params[:reservation]["end_time(4i)"] + ":" + params[:reservation]["end_time(5i)"])
    @reservation.end_time = @end_time
    @reservation.status = params[:status]
    temple_id = params[:reservation][:temple_id]
    @reservation.temple_id = temple_id
    if Reservation.before_start_time(@start_time, @end_time)
      flash[:alert] = "終了時間は開始時間よりも後に設定してください。"
      redirect_to temples_reservations_by_day_path(day: @reservation.day)
    elsif Reservation.reserved?(@start_time, @end_time, temple_id)
      flash[:alert] = "指定された日時は既に予約済みです。"
      redirect_to temples_reservations_by_day_path(day: @reservation.day)
    elsif @reservation.save
      flash[:success] = "下記の日時で予約を行いました。"
      redirect_to complete_reservation_path @reservation.id
    else
      render :new
    end
  end

  def reservations_by_day
    @date = params[:day] ? Date.parse(params[:day]) : Time.zone.today
    start_date = @date.beginning_of_day
    end_date = @date.end_of_day
    @reservations = current_temple.reservations.where(start_time: start_date..end_date).includes(:user)
    session[:search_date] = params[:day]
    @search_date = session[:search_date] || Time.zone.today
  end

  def destroy_by_day
    reservation = Reservation.find(params[:id])
    if reservation.destroy
      redirect_to temples_reservations_by_day_path(day: reservation.start_time.to_date), notice: '予約を削除しました。'
    else
      render :reservations_by_day
    end
  end

  def destroy
    user = User.find(params[:user_id])
    reservation = user.reservations.find(params[:id])
    if reservation.destroy
      redirect_to temples_user_reservations_path(user.id), notice: '予約を削除しました。'
    else
      render :index
    end
  end

  def index
    @user = User.find(params[:user_id])
    @reservations = @user.reservations.where("start_time >= ?", Time.zone.today.beginning_of_day).where(temple_id: current_temple.id).order(:start_time)
  end
  
  def all
    @reservations = current_temple.reservations
    @sorted_reservations = @reservations.order(start_time: :asc)
  end
  
  def show
    @reservation = Reservation.find(params[:id])
  end

  def edit
    @reservation = Reservation.find(params[:id])
    start_time = @reservation.start_time
    @start_times = (9..19).flat_map { |hour| [["#{hour}:00", "#{hour}:00"], ["#{hour}:30", "#{hour}:30"]] }
    @selected_value = start_time.strftime("%H:%M")
    end_time = @reservation.end_time
    @end_times = (9..23).flat_map { |hour| [["#{hour}:00", "#{hour}:00"], ["#{hour}:30", "#{hour}:30"]] }
    @selecteds_value = end_time.strftime("%H:%M")
    user_id = params[:user_id]
    @user = User.find_by(id: user_id)
  end

  def update
    @reservation = Reservation.find(params[:id])
    @reservation.day = params[:reservation][:day]
    @start_time = Time.zone.parse(params[:reservation][:day] + " " + params[:reservation][:time])
    @reservation.start_time = @start_time
    @end_time = Time.zone.parse(params[:reservation][:day] + " " + params[:reservation]["end_times"])
    @reservation.end_time = @end_time
    @reservation.comment = params[:reservation][:comment]
    @reservation.status = params[:status]
    temple_id = params[:reservation][:temple_id]
    @reservation.temple_id = temple_id
    if params[:reservation][:user_id] == "new" && params[:reservation][:new_user_name].present?
      @reservation.new_user_name = params[:reservation][:new_user_name]
    end
    if Reservation.before_start_time(@start_time, @end_time)
      flash[:alert] = "終了時間は開始時間よりも後に設定してください。"
      redirect_to temples_reservations_by_day_path(day: @reservation.day)
    elsif Reservation.reserved?(@start_time, @end_time, @reservation.id, temple_id)
      flash[:alert] = "指定された日時は既に予約済みです。"
      redirect_to temples_reservations_by_day_path(day: @reservation.day)
    elsif @reservation.update(reservation_params)
      updated_date = @reservation.day
      @reservations = Reservation.where(day: updated_date)
      redirect_to temples_reservations_by_day_path(day: updated_date), notice: '予約を編集しました'
    else
      render :edit
    end
  end

  def delete_user
    @reservation = Reservation.find(params[:id])
    @reservation.update(user_id: nil)
    redirect_to edit_temples_reservation_path(@reservation, user_id: nil)
  end
  
  def month
    @temple = Temple.find(params[:temple_id])
  end
  
  def week
    @temple = Temple.find(params[:temple_id])
    @date = Date.parse(params[:date])
    @date_range = @date..(@date + 6.days)
    @reservations = Reservation.all
    if Reservation.check_reservation_days(@date)
      flash[:alert] = "過去の日付は選択できません。"
      render :week
    end
  end
  
  
  private
  
  
  def reservation_params
    params.require(:reservation).permit(:day, :time, :user_id, :temple_id, :start_time, :end_time, :admin_id, :status, :start_date, :end_date, :new_user_name, :comment)
  end

end

app/controllers/temples/sessions_controller.rb
# frozen_string_literal: true

class Temples::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  
  def after_sign_out_path_for(resource)
    new_temple_session_path
  end
  
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
  
  #予約済みの枠を判定
  def find_reservation(reservations, day, start_time, end_time, temple_id)
    reservations.find do |reservation|
      reservation.start_time.to_date == day &&
        reservation.end_time.to_date == day &&
        reservation.start_time <= end_time &&
        reservation.end_time > start_time &&
        reservation.temple_id == temple_id
    end
  end
  
  #カレンダー時間帯の表示
  def times
    times = ["9:00","9:30",
            "10:00","10:30",
            "11:00","11:30",
            "12:00","12:30",
            "13:00","13:30",
            "14:00","14:30",
            "15:00","15:30",
            "16:00","16:30",
            "17:00","17:30",
            "18:00","18:30",
            "19:00","19:30"]
  end
  
end

app/helpers/temples_helper.rb
module TemplesHelper
  
  #ユーザー検索フォームとボタンを表示
  def user_search
    search_field = text_field_tag(:search, params[:search], class: "form-control", placeholder: "名前を入力してください")
    search_button = button_tag(type: "submit", class: "btn btn-outline-primary", id: "button-addon2") do
      content_tag(:i, "", class: "fas fa-search") + "検索"
    end
    search_field + search_button
  end
  
end

app/views/temples/reservations/edit.html.erb
<div class="container days">
  <div class="row col-md-10 clo-sm-11 mx-auto">
    
    <% if @reservation.errors.any? %>
      <%= @reservation.errors.full_messages %>
    <% end %>
    
    <div class="title text-center mt-5 mb-4">
      <h2>予約編集画面</h2>
    </div>
    
    <%= form_with model: @reservation, url: temples_reservation_path(@reservation), method: :patch, local: true do |f| %>
      
      <div class="form-group mb-3">
        <%= f.label :day, "日付", class: "form-label" %>
        <%= f.date_field :day, name: "reservation[day]", id: "reservation-day", class: "form-control" %>
      </div>
        
      <div class="row">
        <div class="form-group my-3 col-6">
          <%= f.label :time, "開始時間", class: "form-label" %>
          <div class="d-flex">
            <%= select_tag "reservation[time]", options_for_select(@start_times, selected: @selected_value), include_blank: false, class: "form-control" %>
          </div>
        </div>
          
        <div class="form-group my-3 col-6">
          <%= f.label :end_time, '終了時間', class: "form-label" %>
          <div class="d-flex">
            <%= select_tag "reservation[end_times]", options_for_select(@end_times, selected: @selecteds_value), include_blank: false, class: 'form-control mr-2' %>
          </div>
        </div>
      </div>
        
      <div class="form-group text-center mt-3">
        <table>
          <tbody>
            <tr>
              <td>
                <% if params[:user_id].present? %>
                  <% @reservation.user_id = params[:user_id] %>
                  <% @user = User.find(params[:user_id]) %>
                  <%= @user.name %>
                  <%= f.hidden_field :user_id, value: @reservation.user_id %>
                <% elsif @reservation.user.present? %>
                  <%= @reservation.user.name %>
                <% end %>
                <% if @reservation.user_id.present? %>
                  <%= link_to "ユーザーを変更", temples_users_path(source: 'edit_temples_users', reservation_id: @reservation.id), class: "btn btn-sm btn-outline-secondary" %>
                  |
                  <%= link_to "削除", delete_user_temples_reservation_path(@reservation, user_id: @reservation.user_id), method: :patch, id: "delete-user-link", class: "btn btn-sm btn-outline-danger" %>
                <% else %>
                  <%= link_to "ユーザーを追加", temples_users_path(source: 'edit_temples_users', reservation_id: @reservation.id), id: 'add-user-link', class: "btn btn-sm btn-outline-success" %>
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>
        
        <div class="form-group mt-3">
          <%= check_box_tag "reservation[user_id]", "new", false, id: "new-user-checkbox" %>
          <%= label_tag "new-user-checkbox", "任意の名前を入力" %>
          <%= text_field_tag "reservation[new_user_name]", nil, id: "new-user-name", placeholder: "ユーザー名を入力してください", class: "form-control d-none" %>
        </div>
        
        <div class="form-group mt-2">
          <%= radio_button_tag(:status, true, @reservation.status == true) %>
          <%= label_tag(:status, "確定") %>
          <%= radio_button_tag(:status, false, @reservation.status == false) %>
          <%= label_tag(:status, "確認中") %>
        </div>
      </div>
        
      <div class="form-group mt-2">
        <%= f.label :comment, '備考欄', class: "form-label" %>
        <%= f.text_area :comment, rows: 5, class: 'form-control' %>
      </div>
        
      <%= f.hidden_field :temple_id, value: current_temple.id %>
        
      <div class="form-group text-center mt-3">
        <%= f.submit "更新", class: "btn btn-outline-primary" %>
      </div>
        
    <% end %>
  </div>
</div>

<%= javascript_pack_tag 'new_user_name' %>

app/views/temples/reservations/index.html.erb
<div class="container">
  <div class="row col-md-10 clo-sm-11 mx-auto">
    
    <div class="title text-center mt-5 mb-4">
      <h2><%= @user.name %>様の予約一覧画面</h2>
    </div>
    
    <div class="text-center">
      <%= link_to temples_user_path(@user) do %>
        <button type="button" class="btn btn-outline-secondary">
          <i class="fas fa-id-card"></i> <%= "#{@user.name}様の登録情報" %>
        </button>
      <% end %>
    </div>
    
    <div class="text-center mt-3">
      <% if @reservations.present? %>
        <p>下記の日時で予約されています。</p>
      <% else %>
        <p>予約がありません。</p>
      <% end %>
    </div>
    
    <table class="table table-responsive user-reservations-table text-center mt-3">
      <% @reservations.each do |reservation| %>
        <tr class="field reserved <%= reservation.status ? 'active' : 'inactive' %>">
          <td><%= reservation.day.strftime('%Y年%m月%d日') %></td>
          <td><%= reservation.start_time.strftime("%H:%M") %>　-　<%= reservation.end_time.strftime("%H:%M") %></td>
          <td>
            <%= link_to "詳細", temples_reservations_by_day_path(day: reservation.day), class: "btn btn-sm btn-outline-primary" %>
            <%= link_to "削除", url_for([:temples, @user, reservation]), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-sm btn-outline-danger" %>
          </td>
        </tr>
      <% end %>
    </table>
    
  </div>
</div>

app/views/temples/reservations/month.html.erb
<div class="container">
  <div class="row">
    
    <div class="col-12 text-center mt-5">
      <h1>予約画面</h1>
    </div>
    
    <%= month_calendar do |date| %>
      <%= date.day %>
    <% end %>
    
    <%= link_to "ホーム", root_path, class: "btn btn-outline-primary mb-5" %>
    
  </div>
</div>

app/views/temples/reservations/new.html.erb
<div class="container">
  <div class="row col-md-10 clo-sm-11 mx-auto">
    
    <% if @reservation.errors.any? %>
      <%= @reservation.errors.full_messages %>
    <% end %>
    
    <div class="title text-center mt-5 mb-4">
      <h1>新規予約画面</h1>
    </div>
    
    <%= form_with model: @reservation, url: temples_reservations_path, local: true, class: 'form' do |f| %>
      
      <div class="form-group mb-3">
        <%= f.label :day, '日付', class: "form-label" %>
        <%= f.text_field :day, class: 'form-control', value: @day, readonly: true %>
      </div>
        
      <div class="row">
        <div class="form-group my-3 col-6">
          <%= f.label :time, '開始時間', class: "form-label" %>
          <%= f.text_field :time, class: 'form-control', value: @time, readonly: true %>
        </div>
        
        <div class="form-group my-3 col-6">
          <%= f.label :end_time, '終了時間', class: "form-label" %>
          <div class="d-flex">
            <%= f.time_select :end_time, { start_hour: 9, end_hour: 23, minute_step: 30, include_seconds: false }, { class: 'form-control mr-2', id: 'end_time_select' } %>
          </div>
        </div>
      </div>
      
      <div class="form-group text-center mt-3">
        <table>
          <tbody>
            <tr>
              <% if params[:user_id].present? %>
                <% @reservation.user_id = params[:user_id] %>
                <%= @user.name %>
                <%= f.hidden_field :user_id, value: @reservation.user_id %>
              <% end %>
              <% if @user_id.present? %>
                <%= link_to "ユーザーを変更", temples_users_path(source: 'new_temples_users', day: @day, time: @time), class: "btn btn-sm btn-outline-secondary" %>
                |
                <%= link_to "削除", new_temples_reservation_path(day: @day, time: @time), id: "delete-user-link", class: "btn btn-sm btn-outline-danger" %>
              <% else %>
                <%= link_to "ユーザーを追加", temples_users_path(source: 'new_temples_users', day: @day, time: @time), id: 'add-user-link', class: "btn btn-sm btn-outline-success" %>
              <% end %>
            </tr>
          </tbody>
        </table>
      
        <div class="form-group mt-3">
          <%= check_box_tag "reservation[user_id]", "new", false, id: "new-user-checkbox" %>
          <%= label_tag "new-user-checkbox", "任意の名前を入力" %>
          <%= text_field_tag "reservation[new_user_name]", nil, id: "new-user-name", placeholder: "ユーザー名を入力してください", class: "form-control d-none" %>
        </div>
        
        <div class="form-group mt-2">
          <%= radio_button_tag(:status, true) %>
          <%= label_tag(:status, "確定") %>
          <%= radio_button_tag(:status, false) %>
          <%= label_tag(:status, "確認中") %>
        </div>
      </div>
        
      <div class="form-group mt-2">
        <%= f.label :comment, '備考欄', class: "form-label" %>
        <%= f.text_area :comment, rows: 5, class: 'form-control' %>
      </div>
        
      <%= f.hidden_field :temple_id, value: current_temple.id %>
      
      <div class="form-group text-center mt-3">
        <%= f.submit value: '予約する', class: 'btn btn-outline-primary' %>
      </div>
        
    <% end %>
  </div>
</div>

<%= javascript_pack_tag 'new_user_name' %>

app/views/temples/reservations/week.html.erb
<div class="container">
  <div class="row">
    
    <div class="col-12 text-center mt-5">
      <h1>予約画面</h1>
    </div>
    
    <%= week_calendar do |date| %>
      <%= date.day %>
    <% end %>
    
    <%= link_to "月カレンダーへ", temples_reservations_month_path(temple_id: @temple), class: "btn btn-outline-primary" %>
    
  </div>
</div>