config/routes.rb
Rails.application.routes.draw do
  
  root 'homes#index'
  
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    registrations: 'users/registrations',
  }
  
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    registrations: 'admins/registrations',
  }
  
  devise_for :temples, controllers: {
    sessions:      'temples/sessions',
    registrations: 'temples/registrations',
  }
  
  namespace :admins do
    resources   :users, only: %i(index show destroy edit update) do
      get 'reservations', on: :member
      get 'reservation',  on: :member
    end
    resources :temples, only: %i(index show destroy edit update)
  end
  
  resources :reservations, only: %i(new create index show destroy update) do
    get 'complete', on: :member
  end
  
  namespace :temples do
    resources :users, only: %i(index show) do
      resources :reservations, only: %i(show index destroy)
    end
    resources :reservations,  only: %i(new create edit update) do
      patch :delete_user,     on:   :member
      get   'all',            on:   :collection
    end
    get     'reservations/month'   =>  'reservations#month'
    get     'reservations/week'    =>  'reservations#week'
    get     'reservations_by_day', to: 'reservations#reservations_by_day', as: 'reservations_by_day'
    delete  'reservations_by_day', to: 'reservations#destroy_by_day',      as: 'destroy_reservations_by_day'
  end
  
  resources :temples, only: [:index, :show] do
    get 'management', to: :collection
  end
  
  post  '/temples/:id/assign_temple', to: 'users#assign_temple',   as: 'assign_temple'
  patch '/users/unassign_temple',     to: 'users#unassign_temple', as: 'unassign_temple'
  
  resources :articles
  resources :posts
  resources :users,  only: [:show]
  resources :admins, only: [:index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admins/temples_controller.rb
class Admins::TemplesController < ApplicationController
  before_action :authenticate_admin!
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def show
    @temple = Temple.find(params[:id])
    @articles = @temple.articles.order(created_at: :desc).limit(3)
    set_latitude_longitude(@temple)
  end
  
  def index
    @reservation = Reservation.all
    @temples = Temple.search(params[:search]).order(:name_kana)
  end
  
  def edit
    @temple = Temple.find(params[:id])
  end

  def update
    @temple = Temple.find(params[:id])
    if @temple.update(temple_params)
      redirect_to admins_temple_path(@temple), notice: '寺院情報を更新しました。'
    else
      flash.now[:danger] = "寺院情報を更新できませんでした。"
      render :edit
    end
  end

  def destroy
    @temple = Temple.find(params[:id])
    if @temple.destroy
      redirect_to admins_temples_path, notice: '寺院を削除しました。'
    else
      flash.now[:danger] = "寺院を削除できませんでした。"
      render :edit
    end
  end
  
  def reservations
    @temple = Temple.find(params[:id])
    @reservations = Reservation.where(temple_id: @temple.id).where("start_time >= ?", Time.zone.today.beginning_of_day).order(:start_time)
  end
  
  def reservation
    @reservation = Reservation.find(params[:id])
    @temple = @reservation.temple
    @user = @reservation.user
  end


  private
  
  # 寺院の住所から緯度と経度を取得しGoogleMapに表示させる
  def set_latitude_longitude(temple)
    result = Geocoder.search(temple.address).first
    if result.present?
      temple.latitude = result.latitude
      temple.longitude = result.longitude
    end
  end

  def temple_params
    if params[:temple][:password].blank? && params[:temple][:password_confirmation].blank?
      params[:temple].delete(:password)
      params[:temple].delete(:password_confirmation)
    end
    params.require(:temple).permit(:name, :name_kana, :postal_code, :prefecture_code, :address, :email, :phone_number, :password, :password_confirmation).except(:current_password)
  end
  
  def configure_permitted_parameters
    if admin_signed_in?
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :name_kana, :postal_code, :prefecture_code, :address, :email, :phone_number])
    else
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :name_kana, :postal_code, :prefecture_code, :address, :email, :phone_number, :password, :password_confirmation, :current_password])
    end
  end
  
  
end

app/controllers/temples/confirmations_controller.rb
# frozen_string_literal: true

class Temples::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/temples/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Temples::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/temples/passwords_controller.rb
# frozen_string_literal: true

class Temples::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/temples/registrations_controller.rb
# frozen_string_literal: true

class Temples::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  
  protected

  def after_update_path_for(resource)
    temple_path(resource)
  end
  
end

app/controllers/temples/reservations_controller.rb
class Temples::ReservationsController < ApplicationController
  before_action :authenticate_temple!, only: [:new, :create, :index, :show, :edit, :update, :destroy, :reservations_by_day, :destroy_by_day, :all, :delete_user]

  def new
    @user_id = params[:user_id]
    @user = User.find_by(id: @user_id)
    @reservation = Reservation.new
    @day = params[:day]
    @time = params[:time]
  end

  def create
    if params[:reservation][:user_id] == 'new'
      @reservation = Reservation.new(reservation_params.merge(new_user_name: params[:reservation][:new_user_name]))
    else
      @reservation = Reservation.new(reservation_params)
    end
    @start_time = Time.zone.parse(params[:reservation][:day] + " " + params[:reservation][:time])
    @reservation.start_time = @start_time
    @end_time = Time.zone.parse(params[:reservation][:day] + " " + params[:reservation]["end_time(4i)"] + ":" + params[:reservation]["end_time(5i)"])
    @reservation.end_time = @end_time
    @reservation.status = params[:status]
    temple_id = params[:reservation][:temple_id]
    @reservation.temple_id = temple_id
    if Reservation.before_start_time(@start_time, @end_time)
      flash[:alert] = "終了時間は開始時間よりも後に設定してください。"
      redirect_to temples_reservations_by_day_path(day: @reservation.day)
    elsif Reservation.reserved?(@start_time, @end_time, temple_id)
      flash[:alert] = "指定された日時は既に予約済みです。"
      redirect_to temples_reservations_by_day_path(day: @reservation.day)
    elsif @reservation.save
      flash[:success] = "下記の日時で予約を行いました。"
      redirect_to complete_reservation_path @reservation.id
    else
      render :new
    end
  end

  def reservations_by_day
    @date = params[:day] ? Date.parse(params[:day]) : Time.zone.today
    start_date = @date.beginning_of_day
    end_date = @date.end_of_day
    @reservations = current_temple.reservations.where(start_time: start_date..end_date).includes(:user)
    session[:search_date] = params[:day]
    @search_date = session[:search_date] || Time.zone.today
  end

  def destroy_by_day
    reservation = Reservation.find(params[:id])
    if reservation.destroy
      redirect_to temples_reservations_by_day_path(day: reservation.start_time.to_date), notice: '予約を削除しました。'
    else
      render :reservations_by_day
    end
  end

  def destroy
    user = User.find(params[:user_id])
    reservation = user.reservations.find(params[:id])
    if reservation.destroy
      redirect_to temples_user_reservations_path(user.id), notice: '予約を削除しました。'
    else
      render :index
    end
  end

  def index
    @user = User.find(params[:user_id])
    @reservations = @user.reservations.where("start_time >= ?", Time.zone.today.beginning_of_day).where(temple_id: current_temple.id).order(:start_time)
  end
  
  def all
    @reservations = current_temple.reservations
    @sorted_reservations = @reservations.order(start_time: :asc)
  end
  
  def show
    @reservation = Reservation.find(params[:id])
  end

  def edit
    @reservation = Reservation.find(params[:id])
    start_time = @reservation.start_time
    @start_times = (9..19).flat_map { |hour| [["#{hour}:00", "#{hour}:00"], ["#{hour}:30", "#{hour}:30"]] }
    @selected_value = start_time.strftime("%H:%M")
    end_time = @reservation.end_time
    @end_times = (9..23).flat_map { |hour| [["#{hour}:00", "#{hour}:00"], ["#{hour}:30", "#{hour}:30"]] }
    @selecteds_value = end_time.strftime("%H:%M")
    user_id = params[:user_id]
    @user = User.find_by(id: user_id)
  end

  def update
    @reservation = Reservation.find(params[:id])
    @reservation.day = params[:reservation][:day]
    @start_time = Time.zone.parse(params[:reservation][:day] + " " + params[:reservation][:time])
    @reservation.start_time = @start_time
    @end_time = Time.zone.parse(params[:reservation][:day] + " " + params[:reservation]["end_times"])
    @reservation.end_time = @end_time
    @reservation.comment = params[:reservation][:comment]
    @reservation.status = params[:status]
    temple_id = params[:reservation][:temple_id]
    @reservation.temple_id = temple_id
    if params[:reservation][:user_id] == "new" && params[:reservation][:new_user_name].present?
      @reservation.new_user_name = params[:reservation][:new_user_name]
    end
    if Reservation.before_start_time(@start_time, @end_time)
      flash[:alert] = "終了時間は開始時間よりも後に設定してください。"
      redirect_to temples_reservations_by_day_path(day: @reservation.day)
    elsif Reservation.reserved?(@start_time, @end_time, @reservation.id, temple_id)
      flash[:alert] = "指定された日時は既に予約済みです。"
      redirect_to temples_reservations_by_day_path(day: @reservation.day)
    elsif @reservation.update(reservation_params)
      updated_date = @reservation.day
      @reservations = Reservation.where(day: updated_date)
      redirect_to temples_reservations_by_day_path(day: updated_date), notice: '予約を編集しました'
    else
      render :edit
    end
  end

  def delete_user
    @reservation = Reservation.find(params[:id])
    @reservation.update(user_id: nil)
    redirect_to edit_temples_reservation_path(@reservation, user_id: nil)
  end
  
  def month
    @temple = Temple.find(params[:temple_id])
  end
  
  def week
    @temple = Temple.find(params[:temple_id])
    @date = Date.parse(params[:date])
    @date_range = @date..(@date + 6.days)
    @reservations = Reservation.all
    if Reservation.check_reservation_days(@date)
      flash[:alert] = "過去の日付は選択できません。"
      render :week
    end
  end
  
  
  private
  
  
  def reservation_params
    params.require(:reservation).permit(:day, :time, :user_id, :temple_id, :start_time, :end_time, :admin_id, :status, :start_date, :end_date, :new_user_name, :comment)
  end

end

app/controllers/temples/sessions_controller.rb
# frozen_string_literal: true

class Temples::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  
  def after_sign_out_path_for(resource)
    new_temple_session_path
  end
  
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/temples/unlocks_controller.rb
# frozen_string_literal: true

class Temples::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/temples/users_controller.rb
class Temples::UsersController < ApplicationController
  before_action :authenticate_temple!
  
  def index
    @temple = current_temple
    subquery = @temple.reservations.select(:user_id)
    user = User.where(id: @temple.users).or(User.where(id: subquery))
    @users = user.search(params[:search]).order(:name_kana)
  end
  
  def show
    @temple = current_temple
    @user = User.find_by(id: params[:id])
    unless @user.present? && (@temple.users.include?(@user) || @temple.reservations.exists?(user_id: @user.id))
      redirect_to temple_path(@temple), alert: "閲覧する権限がありません。"
    end
  end
  
  
end

app/controllers/temples_controller.rb
class TemplesController < ApplicationController
  before_action :authenticate_temple!, only: [:management]
  
  def show
    @temple = Temple.find(params[:id])
    @articles = @temple.articles.order(created_at: :desc).limit(3)
    set_latitude_longitude(@temple)
  end
  
  def index
    @temples = Temple.search(params[:search]).order(:name_kana)
  end
  
  def management
    @temple = Temple.find(params[:temple_id])
  end
  
  
  private
  
  # 寺院の住所から緯度と経度を取得しGoogleMapに表示させる
  def set_latitude_longitude(temple)
    result = Geocoder.search(temple.address).first
    if result.present?
      temple.latitude = result.latitude
      temple.longitude = result.longitude
    end
  end
  
end

app/helpers/temples_helper.rb
module TemplesHelper
  
  #ユーザー検索フォームとボタンを表示
  def user_search
    search_field = text_field_tag(:search, params[:search], class: "form-control", placeholder: "名前を入力してください")
    search_button = button_tag(type: "submit", class: "btn btn-outline-primary", id: "button-addon2") do
      content_tag(:i, "", class: "fas fa-search") + "検索"
    end
    search_field + search_button
  end
  
end

app/views/temples/index.html.erb
<div class="container">
  <div class="row col-md-10 clo-sm-11 mx-auto">
    
    <div class="title text-center mt-5 mb-4">
      <h2>寺院一覧</h2>
    </div>
    
    <div class="temple-search">
      <%= form_tag(temples_path, method: :get, class: "input-group") do %>
        <%= text_field_tag(:search, params[:search], class: "form-control", placeholder: "寺院名を入力してください") %>
        <%= button_tag(type: "submit", class: "btn btn-outline-primary", id: "button-addon2") do %>
          <i class="fas fa-search"></i> 検索
        <% end %>
      <% end %>
    </div>
    
    <table class="table table-responsive temple-table text-center mt-5">
      <% @temples.each do |temple| %>
      <tr class="field">
        <td class="col-md-4">
          <%= image_tag temple.get_profile_image(200, 200) %><br>
          <%= temple.name %><br>
          <%= link_to "寺院詳細", temple_path(temple.id), class: "btn btn-sm btn-outline-primary" %>
        </td>
        <td class="col-md-8"><%= temple.introduction %></td>
      </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/temples/management.html.erb
<div class="container">
    
  <h2 class="text-center mt-5 mb-5">管理メニュー</h2>
  
  <div class="card-list row d-flex justify-content-md-between justify-content-center pt-5">
    
    <div class="card management text-center col-lg-5 col-md-5 col-sm-8 col-10 mb-5">
      <div class="card-body" onclick="location.href='<%= articles_path(temple_id: @temple.id) %>';">
        <div class="card-icon">
          <i class="fas fa-book-open fa-5x" style='color:lightgreen;'></i>
        </div>
        <div class="card-text">
          <p>お知らせ管理</p>
        </div>
      </div>
    </div>
    
    <div class="card management text-center col-lg-5 col-md-5 col-sm-8 col-10 mb-5">
      <div class="card-body" onclick="location.href='<%= temples_users_path(id: @temple.id) %>';">
        <div class="card-icon">
          <i class="fas fa-user fa-5x" style='color:skyblue;'></i>
        </div>
        <div class="card-text">
          <p>ユーザー管理</p>
        </div>
      </div>
    </div>
    
    <div class="card management text-center col-lg-5 col-md-5 col-sm-8 col-10 mb-5">
      <div class="card-body" onclick="location.href='<%= all_temples_reservations_path(id: @temple.id) %>';">
        <div class="card-icon">
          <i class="fas fa-calendar-check fa-5x" style='color:lightpink;'></i>
        </div>
        <div class="card-text">
          <p>予約管理</p>
        </div>
      </div>
    </div>
    
    <div class="card management text-center col-lg-5 col-md-5 col-sm-8 col-10 mb-5">
      <div class="card-body" onclick="location.href='<%= temples_reservations_month_path(temple_id: @temple.id) %>';">
        <div class="card-icon">
          <i class="fas fa-calendar-alt fa-5x" style='color:gold;'></i>
        </div>
        <div class="card-text">
          <p>カレンダー</p>
        </div>
      </div>
    </div>
    
    <div class="card management text-center col-lg-5 col-md-5 col-sm-8 col-10 mb-5">
      <div class="card-body" onclick="location.href='<%= temples_reservations_by_day_path(id: @temple.id, day: Time.zone.today) %>';">
        <div class="card-icon">
          <i class="fas fa-clock fa-5x" style='color:plum;'></i>
        </div>
        <div class="card-text">
          <p>スケジュール</p>
        </div>
      </div>
    </div>
    
  </div>

</div>

app/views/temples/show.html.erb
  <div class="introduction-group">
    <div class="container">
      
      <div class="title text-center mt-5 mb-4">
        <h2><%= @temple.name %></h2>
      </div>
    
      <div class="row">
        <div class="profile row col-lg-6 col-md-10 mx-auto mb-3">
          
          <div class="profile-group">
            <%= image_tag @temple.get_profile_image(600, 400), class: "profile-image" %>
          </div>
        
          <div class="profile-group text-center pt-2">
            <% if temple_signed_in? && @temple.id == current_temple.id %>
              <%= link_to edit_temple_registration_path do %>
                <button class="btn btn-outline-secondary">
                  <i class="fas fa-vihara"></i> プロフィール編集
                </button>
              <% end %>
            <% end %>
          </div>
        
          <div class="profile-group text-center pt-2 row">
            <% if user_signed_in? %>
              <div class="col">
                <% if current_user.temple == @temple %>
                  <%= link_to unassign_temple_path, method: :patch do %>
                    <button type="button" class="btn btn-outline-danger">
                      <i class="fas fa-user-minus"></i> 所属解除
                    </button>
                  <% end %>
                <% else %>
                  <%= link_to assign_temple_path(@temple), method: :post do %>
                    <button type="button" class="btn btn-outline-success">
                      <i class="fas fa-user-plus"></i> 所属する
                    </button>
                  <% end %>
                <% end %>
              </div>
              <div class="col">
                <%= link_to temples_reservations_month_path(temple_id: @temple.id) do %>
                  <button class="btn btn-outline-primary">
                    <i class="far fa-calendar-alt"></i> 予約する
                  </button>
                </div>
              <% end %>
            <% elsif !user_signed_in? && !temple_signed_in? %>
              <p>予約を行うには<%= link_to "ログイン", new_user_session_path %>が必要です。</p>
            <% end %>
          </div>
        </div>
    
        <div class="profile-group col-lg-6 col-md-10 col-sm-10 mx-auto">
          <%= @temple.introduction %>
        </div>
        
      </div>
    </div>
  </div>
    
  <div class="container">
    <div class="card-list-container row my-5">
      <% @articles.each do |article| %>
        <div class="card col-lg-3 col-md-5 col-sm-8 mx-auto mt-4 p-3" onclick="location.href='<%= article_path(temple_id: @temple.id, id: article.id) %>';">
          <div class="card-body">
            <div class="row">
              <h2 class="card-title"><%= article.title %></h2>
              <% if article.content.length <= 70 %>
                <p class="card-text"><%= article.content %></p>
              <% else %>
                <p class="card-text">
                  <%= truncate(article.content, length: 70) %>
                  <small><%= link_to "続きを読む", article_path(temple_id: @temple.id, id: article.id) %></small>
                </p>
              <% end %>
              <small class="text-muted no-link-style"><%= article.formatted_created_at %></small>
            </div>
          </div>
        </div>
      <% end %>
    </div>
      
    <div class="text-center">
      <% if @temple.articles.count > 3 %>
        <h4 class="pt-3 mb-5"><%= link_to '過去のお知らせはこちら', articles_path(temple_id: @temple.id) %></h4>
      <% end %>
    </div>
  </div>
    
  <div class="contact pt-5">
    <h6>お問い合わせ先</h6>
    <p>
      <%= @temple.name %><br>
      〒<%= number_with_hyphen_format(@temple.postal_code) %><br>
      <%= @temple.address_with_prefecture %><br>
      TEL：<%= number_with_hyphen_format(@temple.phone_number) %><br>
    </p>
  </div>

<div class="map">
  <div id="map"></div>
</div>


<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap" async defer></script>
<script>
  function initMap(){

    let mapPosition = {lat: <%= @temple.latitude %> , lng: <%= @temple.longitude %> };
    let map = new google.maps.Map(document.getElementById('map'), {
      zoom: 15,
      center: mapPosition
    });
    let transitLayer = new google.maps.TransitLayer();
    transitLayer.setMap(map);
    
    let contentString = '<%= @temple.address %>';
    let infowindow = new google.maps.InfoWindow({
      content: contentString
    });

    let marker = new google.maps.Marker({
      position: mapPosition,
      map: map,
      title: contentString
    });
  }
</script>